ALTER TABLE "CompanyItemDuty" ADD COLUMN IF NOT EXISTS "specialRatePct" DOUBLE PRECISION;
ALTER TABLE "CompanyItemDuty" ADD COLUMN IF NOT EXISTS "section301RatePct" DOUBLE PRECISION;
ALTER TABLE "CompanyItemDuty" ADD COLUMN IF NOT EXISTS "section232RatePct" DOUBLE PRECISION;
ALTER TABLE "CompanyItemDuty" ADD COLUMN IF NOT EXISTS "ieepaRatePct" DOUBLE PRECISION;
ALTER TABLE "CompanyItemDuty" ADD COLUMN IF NOT EXISTS "additionalRatePct" DOUBLE PRECISION;
