ALTER TABLE "CompanyItemDutyApplication" ADD COLUMN IF NOT EXISTS "specialAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CompanyItemDutyApplication" ADD COLUMN IF NOT EXISTS "section301Amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CompanyItemDutyApplication" ADD COLUMN IF NOT EXISTS "section232Amount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CompanyItemDutyApplication" ADD COLUMN IF NOT EXISTS "ieepaAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CompanyItemDutyApplication" ADD COLUMN IF NOT EXISTS "additionalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
